### ISSUE TITLE
If passive=False, Ra and Cm are not set

### ISSUE THREAD

**Issue by alejoe91** [LFPy/LFPy#175] opened 2020-06-02 14:03 UTC
I encountered this issue while trying to set `Ra` and `cm` without `passive=True`. In that case, `self.Ra`and `self.cm` are set (https://github.com/LFPy/LFPy/blob/master/LFPy/cell.py#L247-L258), but since `_set_passive` is not called the values are not actually set in the sections (https://github.com/LFPy/LFPy/blob/207095689106914e97e12653d680596c710b9b0d/LFPy/cell.py#L512-L519).

I think that Ra and cm should be inserted in any case.

@espenhgn @torbjone do you guys agree? I can make a small PR :)

**Comment by espenhgn** [comment] 2020-06-02 14:30
Yes, this looks like a bug. `sec.Ra` and `sec.cm` should be set also when `passive=False`. 
I think the reason we never spotted this is that with `custom_code=...` that code would usually set these parameters as well.

**Comment by espenhgn** [comment] 2020-06-02 17:17
Merged #176, closing.

**Comment by espenhgn** [comment] 2020-09-03 20:21
Hi @alejoe91 - I'm sorry but we have to revert merging your PR #178 or find some other way to solve this. 
The Hay2011 model and corresponding examples (and potentially other active neuron models) changed behavior with this change set.

See for example the output of `example_loadL5bPCmodelsEH.py`:

Current behavior (since commit SHA 8c96bbeb66fde5e9131f04164767cc3bc1de3359)
![image](https://user-images.githubusercontent.com/2492641/92162735-ee2e2b00-ee32-11ea-8157-2bb6b51305f1.png)

Old behavior (parent SHA 207095689106914e97e12653d680596c710b9b0d)
![image](https://user-images.githubusercontent.com/2492641/92162997-4d8c3b00-ee33-11ea-807d-071c9af96543.png)

**Comment by alejoe91** [comment] 2020-09-03 20:32
Hi @espenhgn 

How can setting Ra and cm (like this PR does) be the responsible for this behavior? 

I guess this is because the custom code is setting those Paramus as well. Then when custom_code is used, _set_passive_params should not be called. So we should just check if custom_code is not None

**Comment by espenhgn** [comment] 2020-09-04 07:08
Hi @alejoe91. This particular example file was supposed to reproduce fig4B of Hay et al 2011, which it indeed used to do. 

Without going through the entire chain of events when creating the model, I presume TemplateCell subclass uses the template file which itself reads in the morphology and a biophysical specification file which includes the full specification of the cell. Then the parent Cell class is initialized, which results in `cm` and `Ra` being reset to whatever default values are present in LFPy.Cell.

**Comment by espenhgn** [comment] 2020-09-04 07:17
As to why `TemplateCell` somewhat unusually initialize the parent class at the end of it's `__init__` function the reason must be that some cell attributes must be set before calling the monkeypatched `_load_geometry()` and `_create_sectionlist()` methods

**Closed as completed** 2020-09-04 08:10 UTC
Labels: bug
